services:
  app:
    build:
      target: production
    environment:
      APP_ENV: production
      APP_DEBUG: "false"

  # En producción, mapeamos Nginx directamente al puerto 80 (o 443 con SSL)
  nginx:
    ports:
      - "80:80"

  # Ocultamos puertos de base de datos y redis para mayor seguridad
  db:
    ports: []
    restart: always

  redis:
    ports: []
    restart: always

  queue:
    build:
      target: production
    restart: always

  scheduler:
    build:
      target: production
    restart: always

# Desactivamos perfiles de desarrollo
profiles: []
